In [1]:
import cv2 
import numpy as np

In [2]:
img = cv2.imread('2022-01-11-18-12-49-909.jpg')
cv2.imshow("original",img)

In [11]:
cv2.destroyAllWindows()

In [6]:
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
blur = cv2.GaussianBlur(gray,(5,5),0)

thresh = cv2.adaptiveThreshold(blur,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY_INV,11,1)
cv2.imshow("thresh",thresh)
cv2.waitKey(1)

-1

In [8]:
contours,herarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
print(len(contours))

6281


In [10]:
filtered = []
for c in contours:
    if cv2.contourArea(c) < 1000:
        continue
    filtered.append(c)
print(len(filtered)) 


objects = np.zeros([img.shape[0],img.shape[1],3], 'uint8') 
print(objects)
col = (np.random.randint(0,255),np.random.randint(0,255),np.random.randint(0,255))
cv2.drawContours(objects,filtered,-1,col,-1)  
area = cv2.contourArea(c)
print(area)

cv2.imshow("Contours",objects)
cv2.waitKey(1)


25
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
0.0


-1

In [7]:
import cv2
import numpy as np

In [13]:
template = cv2.imread('2022-01-11-18-12-49-909')
frame = cv2.imread('2022-01-11-18-12-49-909')

In [ ]:
res = cv2.matchTemplate(frame,template,cv2.TM_CCOEFF_NORMED)
cv2.imshow("Macthing",res)
cv2.waitKey(0)

In [2]:
import cv2 
import numpy as np

In [8]:
img = cv2.imread('2022-01-11-18-12-49-909.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
path = "haarcascade_frontalface_default.xml"
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades +path)
faces = face_cascade.detectMultiScale(gray,scaleFactor = 1.05,minNeighbors = 5,minSize = (40,40))
print(len(faces))
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
cv2.imshow("Image",img)
cv2.waitKey(1)  

5


-1

In [13]:
cv2.destroyAllWindows()

In [12]:
img = cv2.imread('2022-01-11-18-12-49-909.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
path = "haarcascade_eye.xml"
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
eyes = eye_cascade.detectMultiScale(gray,scaleFactor = 1.02,minNeighbors= 20,minSize = (10,10) )
print(len(eyes))
for (x,y,w,h) in eyes:
    xc = (x+ x+w)/2
    yc = (y+ y+h)/2
    radius = w/2
    cv2.circle(img,(int(xc),int(yc)),int(radius),(255,0,0),2)
cv2.imshow("eyes",img)
cv2.waitKey(1)    

11


-1